### ISSUE TITLE
Support multiple strains, or URL mounts

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-simulator#105]
Here is a config I am using:

```
staticRoot: /webroot
directoryIndex: index.html

strains:
    launch-docs:
        url: http://localhost:3000/docs/launch
        content: https://github.com/Adobe-Marketing-Cloud/reactor-user-docs.git#master
        directoryIndex: README.html
```

When I run `hlx up`, the "root" URL of the site loads fine. However, trying to load the sub-path `http://localhost:3000/docs/launch` yields a 404. In the above config, this path is mounted using the `url` directive or property or whatever it is called, and points to some external repo.

The logs from this 404 request look like this from `hlx up` output:

```
[hlx] debug: resolved /docs/launch/README.html -> html
[hlx] silly: before
[hlx] debug: Constructing HTML Pipeline
[hlx] debug: Creating pipeline
[hlx] debug: Running HTML pipeline
[hlx] silly: processing
[hlx] debug: Coercing secrets
[hlx] debug: fetching Markdown from http://127.0.0.1:57503/raw/helix/content/master/docs/launch/README.md
[git] debug: [rawHandler] resource not found: file not found: docs/launch/README.md
[hlx] error: Could not fetch Markdown from http://127.0.0.1:57503/raw/helix/content/master/docs/launch/README.md
```

It seems like local helix is trying to find the markdown from the mounted repo in the "current" or local repo.

I am happy to try to fix this, but I am still wrapping my head understanding how all of this is pieced together.

Another thought: would be nice to not map the `url` property to hostnames, but just to paths. Maybe I'm doing this wrong... probably I'm doing this wrong...
