### ISSUE TITLE
Errors retrieving content when repo uses branch name with slash in it

### ISSUE THREAD

**Issue by filmaj** [adobe/helix-simulator#151]
I think if you have a forward slash in your repo branch name, helix no likey, e.g. the initial branch greenkeeper creates is called `greenkeeper/initial` and I see this in the logs when I try to run `hlx up`:

```[0-0] [hlx] error: Could not find Markdown at http://127.0.0.1:54118/raw/helix/content/greenkeeper/initial/index.md```

**Comment by kptdobe** [comment]
This is a known limitation. Nothing we can really do about it. It is impossible to parse the branch name from the Git URLs if it contains a slash. On GitHub, they must resolve it by requesting the list of branch and do a match. This would be too expansive.

**Comment by filmaj** [comment]
Aw, well then I guess we can't use greenkeeper 😞

**Comment by tripodsan** [comment]
@filmaj: what's the canonical strain config for this problem?

**Comment by tripodsan** [comment]
> It is impossible to parse the branch name from the Git URLs if it contains a slash.

this is not true. that's why we added the `.git` suffix to the config. eg: 
`https://gituhb.com/helix/content.git#greenkeeper/initial` should work. right?

**Comment by filmaj** [comment]
The greenkeeper PR is here: https://github.com/adobe/developer.adobe.com/pull/146. The config you can see in the root of the same repo: https://github.com/adobe/developer.adobe.com

Since the failing test hits localhost:3000, I think the canonical config relevant in the failing test case is:

```
definitions:
  defaults:
    - &defaultRepo "http://localhost/local/default.git"
  strains:
    base:
      &basestrain
      code: *defaultRepo
      content: *defaultRepo
      static: *defaultRepo
      package: 16cd39e4810356ecc384bb5185f081e23cae229b

strains:
  default:
    <<: *basestrain
    package: 9e81a2d5d82f2a22bf218b446da32414f33c0d87
```

The failing test:

1. Hits http://localhost:3000. This triggers the developer.adobe.com repo's `content`, which is housed inside [`index.md`](https://github.com/adobe/developer.adobe.com/blob/master/index.md). 
2. Then helix seems to error out as it (I think) proxies to some kind of local git repo hosted on a random port, which is supposed to emulate the content repo IIUC:

```
[0-0] [hlx] error: Could not find Markdown at http://127.0.0.1:54118/raw/helix/content/greenkeeper/initial/index.md
```

My assumption is that this git server is incorrectly interpreting slashes in the branch name as file path slashes inside the repo - so it is probably looking for a `greenkeeper` branch (which doesn't exist) and a filepath of `initial/index.md` (which also doesn't exist). Instead it should be looking for a `greenkeeper/initial` branch and a filepath of `index.md`.

**Comment by tripodsan** [comment]
but where/how do you request the content? I don't see where you set the `content` repo?

**Comment by filmaj** [comment]
The `content` is set in the `basestrain`: `content: *defaultRepo`
.. and the defaults set `&defaultRepo`: `&defaultRepo "http://localhost/local/default.git"`

**Comment by tripodsan** [comment]
but why would it request a different branch? ah, do you mean, your local checkout is on that branch when running `hlx up` ?

**Comment by filmaj** [comment]
> do you mean, your local checkout is on that branch when running `hlx up` ?

exactly so

**Comment by tripodsan** [comment]
this is a problem of the git-server: https://github.com/adobe/git-server/issues/53

but it might be circumvented by treating the current checkout as `master`

**Comment by tripodsan** [comment]
@filmaj unfortunately, it's not possible today. I can try to cheat in the helix-simulator and always use the master branch, but then you won't get the changes of the new branch.

possible solutions:

### 1. fix in git-server
this is probably a good thing to do, anyways.

### 2. disable true git-support in git-server
right now, the git-server acts as hybrid, to try to deliver the blob from the correct branch first, and only falls back to the locally modified files, if the file is checked out (and modified). for me, this is a bit confusing, and I wonder if we really need to support delivering blobs from the repository at all.

in the `hlx up` context, we probably always want to see the local content from the filesystem.
there is only 1 use case: if the current branch contains different code, but you want to see (static) content from a different branch. but even then, the behaviour is probably confusing, and might be enabled/disable with a flag.

### 3. workaround in ci
@filmaj, in circle ci you could have a special workflow for all `greenkeeper/*` branches, that copies the current branch before testing. eg just do a `git co -b greenkeeper_initial`.

**Comment by stefan-guggisberg** [comment]
I'll have a look at 1, i.e. adobe/git-server#53.

**Comment by filmaj** [comment]
Thanks everyone, this is great! I'm not in a massive rush on this... whenever this ends up being fixed, I'll then merge the greenkeeper PR.

**Comment by stefan-guggisberg** [comment]
adobe/git-server#53 is fixed

**Comment by stefan-guggisberg** [comment]
i published adobe/git-server v0.9.14

**Comment by tripodsan** [comment]
FWIW, I also tested this on fastly.

here's my config:

```yaml
definitions:
  repos:
    - &myRepo https://github.com/tripodsan/hlxtest.git#master
    - &myFooRepo https://github.com/tripodsan/hlxtest.git#foo/bar
    - &defaultRepo "http://localhost/local/default.git"

strains:
  dev:
    url: http://localhost:3000/
    code: *defaultRepo
    content: *defaultRepo
    static: *defaultRepo

  subtest:
    url: https://www.99productrules.com/api/general
    code: *myRepo
    content: *myFooRepo
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master

  default:
    code: *myRepo
    content: *myRepo
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
```

### And then the test:

request to https://www.99productrules.com/ shows:

```
helix-logo

Helix - hlxtest (on master) =======================

It works!
```

request to https://www.99productrules.com/api/general/ shows the different content on the `foo/bar` branch:

```
content
helix-logo

Modifed index on foo/bar
It works!
```

/cc @filmaj @trieloff
