### ISSUE TITLE
content URL remapping doesn't work (anymore)

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#186]
Having a strain configured with an content URL that addresses a path in the git repository, doesn't map the request path correctly. eg:

```
strains:
  - name: api
    url: https://www.99productrules.com/api/general
    code: *defaultRepo
    content: https://github.com/tripodsan/hlxtest.git/docs#master
    static: https://github.com/tripodsan/hlxtest.git/htdocs#master
```

should map a request `https://www.99productrules.com/api/general/index.html` to `https://github.com/tripodsan/hlxtest.git/docs/index.md`.

currently, it ignores the `path` in the content url, and tries to fetch: `https://github.com/tripodsan/hlxtest.git/index.md`.

(this works when deployed to the edge)
