### ISSUE TITLE
Add support for new condition language

### ISSUE THREAD

**Issue by tripodsan** [adobe/helix-simulator#277]
with https://github.com/adobe/helix-shared/issues/20 we introduced a condition language that is currently not supported/used by neither helix-simulator nor helix-publish.

it would be good to improve the strain selection in the simulator to support the conditions.

**Comment by dominique-pfister** [comment]
The strains in the simulator use `url` and `urls` outside the condition element, e.g.:
```
local:
    <<: *default
    url: http://localhost:3000/

  website:
    <<: *default
    urls:
      - http://project-helix.io/
      - http://www.project-helix.io/
```
What shall happen with those? I'm asking because `HelixProject.selectStrain` currently selects the strain based on those fields, and there's a comment:
```
// todo: use strain conditions, once implemented. for now, just use request.headers.host
```
